import '../packages/presta/test'
import '../packages/html/test'
import '../packages/adapter-netlify/test'
import '../packages/load/test'
import '../packages/adapter-vercel/test'
import '../packages/utils/test'
import '../packages/adapter-node/test'
import '../packages/adapter-cloudflare-workers/test'
