name = "presta-example-cloudflare-workers"
type = "javascript"

account_id = '0058269086e8cbec458f02e3e7bd036b'
workers_dev = true
compatibility_date = "2022-01-22"

[site]
  bucket = 'build/static'
  entry-point = 'build'

[build]
  command = ''

[build.upload]
  format = 'service-worker'
