name = "presta-cloudflare-workers"
type = "javascript"

zone_id = ''
account_id = ''
route = ''
workers_dev = true
compatibility_date = "2022-01-22"

[site]
  bucket = 'build/static'
  entry-point = 'build'

[build]
  command = ''

[build.upload]
  format = 'service-worker'